common_args:
  dataset_name: bluegreen

experiments:
  kontrast:
    - omega: 15
      mode: 'BG'
      dataset_size: 10000
      epoch: 50
      batch_size: 5000
      lstm_hidden_dim: 30
      lstm_output_dim: 30
      lr: 0.001
